dist: focal
language: node_js
node_js: "7"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.5
  - export PATH="$HOME/.yarn/bin:$PATH"
cache: yarn
install:
  - yarn install
script:
  - yarn lint
  - yarn test --watchAll=false
  - yarn build
  - yarn render
